package Lab12;
import java.awt.*;
import simView.*;

public class air_conditioner extends ViewableDigraph
{

	public air_conditioner(){
		this("air_conditioner",10,10);
	}
	public air_conditioner(String name, double controller_time, double sensor_time)
	{
		super(name);
    	
		addInport("in"); //air_conditioning_system의 user와 연결된 포트
		
		ViewableAtomic c = new controller("controller", controller_time);
		ViewableAtomic t = new temp_sensor("temp_sensor", sensor_time);
    	
		add(c);
		//시뮬레이터에 모델을 등록.
		add(t);
  
		//gpt모델을 커플링 시킨 코드.
		
		addCoupling(this, "in", c, "in1");
		addCoupling(c, "out", t, "in");
		addCoupling(t, "out", c, "in2");
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(707, 366);
        ((ViewableComponent)withName("temp_sensor")).setPreferredLocation(new Point(380, 274));
        ((ViewableComponent)withName("controller")).setPreferredLocation(new Point(219, 66));
    }
}
