package SimpArc;
import java.awt.*;
import simView.*;

public class gpt extends ViewableDigraph
{

	public gpt()
	{
		super("gpt");
    	
		ViewableAtomic g = new genr("g", 10);
		//¾î¶² ¸ðµ¨À» °¡Á®´Ù ¾µ°ÇÁö.
		ViewableAtomic p = new proc("p", 10);
		ViewableAtomic t = new transd("t", 70);
    	
		add(g);
		//½Ã¹Ä·¹ÀÌÅÍ¿¡ ¸ðµ¨À» µî·Ï.
		add(p);
		add(t);
  
		//gpt¸ðµ¨À» Ä¿ÇÃ¸µ ½ÃÅ² ÄÚµå.
		addCoupling(g, "out", p, "in");
		//°¢ ¸ðµ¨µé ³¢¸® ¿¬°áÀ» ½ÃÅ´.
		//(1¸ðµ¨ ÀÌ¸§, 1¸ðµ¨ÀÇ ¾Æ¿ôÇ²Æ÷Æ®, 2¸ðµ¨ ÀÌ¸§, 2¸ðµ¨ÀÇ ÀÎÇ²)
		addCoupling(g, "out", t, "ariv");
		
		addCoupling(p, "out", t, "solved");
     
		addCoupling(t, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
    	preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("t")).setPreferredLocation(new Point(639, 117));
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(465, 476));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(59, 148));
    }
//    preferredSize = new Dimension(988, 646);
//    ((ViewableComponent)withName("t")).setPreferredLocation(new Point(639, 117));
//    ((ViewableComponent)withName("p")).setPreferredLocation(new Point(465, 476));
//    ((ViewableComponent)withName("g")).setPreferredLocation(new Point(59, 148));
}
