package Lab3;
import java.awt.*;
import simView.*;

public class model extends ViewableDigraph
{

	public model()
	{
		super("model");
    	
		ViewableAtomic g = new user("user", 10);
		ViewableAtomic p = new calc("add", 10);
	
    	
		add(g);
		add(p);
		
		addCoupling(g, "out", p, "in");
		addCoupling(p, "out", g, "in");
		
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("add")).setPreferredLocation(new Point(322, 430));
        ((ViewableComponent)withName("user")).setPreferredLocation(new Point(350, 126));
    }
}
