package Lab4;
import java.awt.*;
import simView.*;

public class accumulator_function extends ViewableDigraph
{

	public accumulator_function()
	{
		super("accumulator_function");
    	
		ViewableAtomic g = new user("user", 10);
		ViewableAtomic p = new accumulator("accumulator", 10);
    	
		add(g);
		add(p);
  
		addCoupling(g, "out", p, "in");
		addCoupling(p, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(628, 232);
        ((ViewableComponent)withName("accumulator")).setPreferredLocation(new Point(325, 145));
        ((ViewableComponent)withName("user")).setPreferredLocation(new Point(335, 35));
    }
}
