package Lab11;
import java.awt.*;
import simView.*;

public class gpt extends ViewableDigraph
{

	public gpt()
	{
		super("gpt");
    	
		ViewableAtomic g = new Generator("Generator", 30);
		ViewableAtomic p = new Prosessor("Processor", 70);
		ViewableAtomic q = new queue("Queue", 10);
    	
		add(g);
		//시뮬레이터에 모델을 등록.
		add(p);
		add(q);
  
		//gpt모델을 커플링 시킨 코드.
		addCoupling(g, "out", q, "in_1");
		addCoupling(q, "out", p, "in");
		addCoupling(p, "out_2", q, "in_2");
		addCoupling(p, "out_1", g, "in");
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("Generator")).setPreferredLocation(new Point(175, 213));
        ((ViewableComponent)withName("Queue")).setPreferredLocation(new Point(597, 99));
        ((ViewableComponent)withName("Processor")).setPreferredLocation(new Point(549, 430));
    }
}
